# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
    - v1*
    exclude:
    - v2.0
pr:
  branches:
    include:
      - refs/tags/v1*
    exclude:
      - 'refs/tags/v2.0'
      - '*'


pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'



- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'CLI'
    configMode: 'file'


- task: SonarQubeAnalyze@5

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'alertvcs/retail'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'